swagger: "2.0"
info:
  description: >-
    Documentation for the guidStore API
  version: 1.0.0
  title: guidStore
# for now, should point to your local machine
host: https://localhost:5001
# basePath prefixes all resource paths
basePath: /api
schemes:
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
tags:
  - name: guidStore
    description: Stores and retrieves guid objects
paths:
  /guid/{guid}:
    post:
      tags:
        - guid
      summary: Creates a new guid object
      parameters:
        - in: path
          name: guid
          description: The guid to write to the database.  If not provided, a guid will be generated and returned
          type: string
          required: false
        - in: body
          name: guidData
          description: guid object to add
          required: true
          schema:
            $ref: "#/definitions/guidDef"
      responses:
        200:
          description: Success
          schema:
            type: object
            items:
              $ref: "#/definitions/guidDef"
        400:
          description: Bad Request - typically if the guid already exists
        500:
          description: Internal Error - typically a problem writing the record to the database

# complex objects have schema definitions
definitions:
  guidDef:
    $ref: "./models/guidDef.yaml"
